### ISSUE TITLE
Add more detailed requirements

### ISSUE THREAD

**Issue by vankooch** [InvoicePlane/Wiki#1]
Hi,

thanks for this project, great work. I've installed InvoicePlane on FreeBSD and had some problems with missing php5 modules. This is a list of pkg needed in order to run without problems:
- php5-hash
- php5-mcrypt
- php5-json
- php5-zlib
- php5-openssl (optional)
- php5-recode
- php5-xmlrpc

Maybe you can mention it in the docs.

Regards

**Comment by aidik** [comment]
F... yeah!

Thank you for posting this.
